# Generated by Django 5.2.8 on 2025-11-17 01:45

import apps.core.managers
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        help_text="Email usado para login",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Telefone de contato",
                        max_length=20,
                        null=True,
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Foto de perfil do usuário",
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("manager", "Gerente"),
                            ("user", "Usuário"),
                            ("viewer", "Visualizador"),
                        ],
                        default="user",
                        help_text="Função/permissão do usuário no tenant",
                        max_length=50,
                        verbose_name="Função",
                    ),
                ),
                (
                    "onboarding_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o usuário completou o onboarding",
                        verbose_name="Onboarding Completo",
                    ),
                ),
                (
                    "onboarding_step",
                    models.IntegerField(
                        default=0,
                        help_text="Etapa atual do onboarding (0-4)",
                        verbose_name="Etapa do Onboarding",
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.IntegerField(
                        default=0,
                        help_text="Número de tentativas de login falhas consecutivas",
                        verbose_name="Tentativas de Login Falhas",
                    ),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora até a qual a conta está bloqueada",
                        null=True,
                        verbose_name="Bloqueado até",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant ao qual este usuário pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
                "ordering": ["email"],
            },
            managers=[
                ("objects", apps.core.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="OnboardingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "step",
                    models.IntegerField(
                        default=0,
                        help_text="Etapa atual do onboarding (0-4)",
                        verbose_name="Etapa Atual",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o onboarding foi completado",
                        verbose_name="Completo",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Dados coletados durante o onboarding",
                        verbose_name="Dados Coletados",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        help_text="Tenant que está fazendo onboarding",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progresso do Onboarding",
                "verbose_name_plural": "Progressos de Onboarding",
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.CharField(
                        help_text="Token único para reset de senha",
                        max_length=64,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Data/hora de expiração do token", verbose_name="Expira em"
                    ),
                ),
                (
                    "used",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o token já foi usado",
                        verbose_name="Usado",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuário que solicitou o reset de senha",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Reset de Senha",
                "verbose_name_plural": "Tokens de Reset de Senha",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email", "tenant"], name="core_user_email_d9348c_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["tenant", "is_active"], name="core_user_tenant__18211d_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["tenant", "role"], name="core_user_tenant__469ef1_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingprogress",
            index=models.Index(
                fields=["tenant", "completed"], name="core_onboar_tenant__def953_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(fields=["token", "used"], name="core_passwo_token_024dc6_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(fields=["expires_at"], name="core_passwo_expires_71ae22_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(fields=["user", "used"], name="core_passwo_user_id_2397bf_idx"),
        ),
    ]
