# Generated by Django 5.2.8 on 2025-11-16 23:58

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nome da empresa/cliente", max_length=255, verbose_name="Nome"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador único da URL (ex: empresa-abc)",
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Slug deve conter apenas letras minúsculas, números e hífens",
                                regex="^[a-z0-9-]+$",
                            )
                        ],
                        verbose_name="Slug",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="Domínio do tenant (ex: empresa.structurone.com)",
                        max_length=255,
                        unique=True,
                        verbose_name="Domínio",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email de contato principal", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Telefone de contato",
                        max_length=20,
                        null=True,
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Se o tenant está ativo", verbose_name="Ativo"
                    ),
                ),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[
                            ("free", "Gratuito"),
                            ("basic", "Básico"),
                            ("professional", "Profissional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="basic",
                        help_text="Plano de assinatura",
                        max_length=50,
                        verbose_name="Plano",
                    ),
                ),
                (
                    "subscription_start_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Data de início da assinatura",
                        verbose_name="Data de Início",
                    ),
                ),
                (
                    "subscription_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Data de término da assinatura (opcional)",
                        null=True,
                        verbose_name="Data de Término",
                    ),
                ),
                (
                    "max_projects",
                    models.IntegerField(
                        default=10,
                        help_text="Número máximo de projetos permitidos",
                        verbose_name="Máximo de Projetos",
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(
                        default=5,
                        help_text="Número máximo de usuários permitidos",
                        verbose_name="Máximo de Usuários",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Observações internas sobre o tenant",
                        null=True,
                        verbose_name="Observações",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="tenants_ten_slug_63daca_idx"),
                    models.Index(fields=["domain"], name="tenants_ten_domain_a84b8d_idx"),
                    models.Index(fields=["is_active"], name="tenants_ten_is_acti_8f654a_idx"),
                ],
            },
        ),
    ]
