# Generated by Django 5.2.8 on 2025-11-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="country",
            field=models.CharField(
                choices=[
                    ("BR", "Brasil"),
                    ("US", "Estados Unidos"),
                    ("MX", "México"),
                    ("ES", "Espanha"),
                    ("AR", "Argentina"),
                    ("CO", "Colômbia"),
                    ("CL", "Chile"),
                    ("PE", "Peru"),
                    ("EC", "Equador"),
                    ("VE", "Venezuela"),
                    ("UY", "Uruguai"),
                    ("PY", "Paraguai"),
                    ("BO", "Bolívia"),
                    ("CR", "Costa Rica"),
                    ("PA", "Panamá"),
                    ("GT", "Guatemala"),
                    ("DO", "República Dominicana"),
                    ("CU", "Cuba"),
                    ("HN", "Honduras"),
                    ("NI", "Nicarágua"),
                    ("SV", "El Salvador"),
                ],
                default="BR",
                help_text="País do tenant",
                max_length=2,
                verbose_name="País",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="currency",
            field=models.CharField(
                choices=[
                    ("BRL", "Real Brasileiro (R$)"),
                    ("USD", "Dólar Americano ($)"),
                    ("EUR", "Euro (€)"),
                    ("MXN", "Peso Mexicano (MX$)"),
                    ("ARS", "Peso Argentino ($)"),
                    ("COP", "Peso Colombiano ($)"),
                    ("CLP", "Peso Chileno ($)"),
                    ("PEN", "Sol Peruano (S/)"),
                    ("UYU", "Peso Uruguaio ($U)"),
                    ("PYG", "Guarani Paraguaio (₲)"),
                    ("BOB", "Boliviano (Bs.)"),
                    ("CRC", "Colón Costarriquenho (₡)"),
                    ("DOP", "Peso Dominicano (RD$)"),
                    ("CUP", "Peso Cubano ($)"),
                    ("GTQ", "Quetzal Guatemalteco (Q)"),
                    ("HNL", "Lempira Hondurenha (L)"),
                    ("NIO", "Córdoba Nicaraguense (C$)"),
                    ("PAB", "Balboa Panamenho (B/.)"),
                    ("SVC", "Colón Salvadorenho (₡)"),
                ],
                default="BRL",
                help_text="Moeda padrão do tenant",
                max_length=3,
                verbose_name="Moeda",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="date_format",
            field=models.CharField(
                choices=[
                    ("DD/MM/YYYY", "DD/MM/YYYY"),
                    ("MM/DD/YYYY", "MM/DD/YYYY"),
                    ("YYYY-MM-DD", "YYYY-MM-DD"),
                ],
                default="DD/MM/YYYY",
                help_text="Formato de exibição de datas",
                max_length=20,
                verbose_name="Formato de Data",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="language",
            field=models.CharField(
                choices=[
                    ("pt-br", "Português (Brasil)"),
                    ("en-us", "English (US)"),
                    ("es-es", "Español (España)"),
                ],
                default="pt-br",
                help_text="Idioma padrão do tenant",
                max_length=10,
                verbose_name="Idioma",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="number_format",
            field=models.CharField(
                choices=[("1.234,56", "1.234,56 (Brasil/Espanha)"), ("1,234.56", "1,234.56 (EUA)")],
                default="1.234,56",
                help_text="Formato de exibição de números decimais",
                max_length=20,
                verbose_name="Formato de Número",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="timezone",
            field=models.CharField(
                default="America/Sao_Paulo",
                help_text="Fuso horário do tenant",
                max_length=50,
                verbose_name="Fuso Horário",
            ),
        ),
    ]
