# Generated by Django 5.2.8 on 2025-11-17 03:09

import apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_add_i18n_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="subscription_start_date",
            field=models.DateField(
                default=apps.tenants.models.get_default_subscription_start_date,
                help_text="Data de início da assinatura",
                verbose_name="Data de Início",
            ),
        ),
    ]
